In [4]:
import numpy as np

・様々なndarray

np.arange([start,] stop[, step])

In [6]:
np.arange(0, 5, 2)

array([0, 2, 4])

In [8]:
np.arange(0, 8, 2)

array([0, 2, 4, 6])

In [9]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [10]:
np.arange(0, 100, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

・np.linspace(start, stop, num=50)

In [14]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

・.copy() 
・NumPy Arrayは関数に渡すとき，参照渡しになる
・基本的にデータ量が巨大になる可能性があるものは参照渡し，そうでなければ基本値渡し