・NumPy

In [3]:
import numpy as np

In [4]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [5]:
np_list = np.array([[1,2,3], [1,2,3],[1,2,3]])
np_list

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [6]:
array1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
array2 = np.array([[1,3,5], [2,4,6], [7,8,9]])

In [7]:
array1 + array2

array([[ 2,  5,  8],
       [ 6,  9, 12],
       [14, 16, 18]])

In [8]:
array1 - array2

array([[ 0, -1, -2],
       [ 2,  1,  0],
       [ 0,  0,  0]])

In [9]:
array1 * array2

array([[ 1,  6, 15],
       [ 8, 20, 36],
       [49, 64, 81]])

In [10]:
array1 / array2

array([[1.        , 0.66666667, 0.6       ],
       [2.        , 1.25      , 1.        ],
       [1.        , 1.        , 1.        ]])

In [11]:
array1.shape

(3, 3)

In [12]:
array3 = np.array([[4,5,6]])
array4 = np.array([[1,2,3], [7,8,9]])

In [13]:
array3 + array4

array([[ 5,  7,  9],
       [11, 13, 15]])

In [14]:
array3 * array4

array([[ 4, 10, 18],
       [28, 40, 54]])

In [15]:
array5 = np.array([5])

In [16]:
array1 + array5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])