In [1]:
import numpy as np

・Indexing

In [2]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
print(ndarray)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
print(ndarray[1][0])
print(ndarray[1, 0])

3
3


・Slicing

In [4]:
array = np.array([[1, 2, 3, 4], [2, 4, 6, 4], [3, 5, 6, 8], [2, 9, 10, 6]])
array

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  4],
       [ 3,  5,  6,  8],
       [ 2,  9, 10,  6]])

In [5]:
array[:, 2:]

array([[ 3,  4],
       [ 6,  4],
       [ 6,  8],
       [10,  6]])

In [6]:
array[1:, 2:]

array([[ 6,  4],
       [ 6,  8],
       [10,  6]])

In [7]:
array[1:, 3:]

array([[4],
       [8],
       [6]])

In [8]:
array[:, 1:]

array([[ 2,  3,  4],
       [ 4,  6,  4],
       [ 5,  6,  8],
       [ 9, 10,  6]])